# Generated by Django 4.0 on 2021-12-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tviteras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('hendl', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=255)),
                ('lokacija', models.CharField(max_length=50)),
                ('datum_pridruzivanja', models.DateField(auto_now_add=True)),
                ('pratitelji', models.ManyToManyField(related_name='pracen_od', to='main.Tviteras')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tvit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijelo', models.CharField(max_length=255)),
                ('vrijeme_stvaranja', models.DateTimeField(auto_now_add=True)),
                ('stvorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvitovi', to='auth.user')),
            ],
            options={
                'ordering': ('-vrijeme_stvaranja',),
            },
        ),
        migrations.CreateModel(
            name='Lajk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_lajkanja', models.DateTimeField(auto_now_add=True)),
                ('stvorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lajkovi', to='auth.user')),
                ('tvit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lajkovi', to='main.tvit')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijelo', models.CharField(max_length=255)),
                ('vrijeme_komentiranja', models.DateTimeField(auto_now_add=True)),
                ('stvorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to='auth.user')),
                ('tvit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to='main.tvit')),
            ],
            options={
                'ordering': ('-vrijeme_komentiranja',),
            },
        ),
    ]
