# Generated by Django 4.0 on 2021-12-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tviteras',
            old_name='user',
            new_name='korisnik',
        ),
    ]
