# Generated by Django 4.0 on 2022-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_tviteras_korisnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviteras',
            name='pratitelji',
            field=models.ManyToManyField(blank=True, related_name='pracen_od', to='main.Tviteras'),
        ),
    ]
