# Generated by Django 4.0 on 2022-02-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tviteras_pratitelji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tviteras',
            old_name='pratitelji',
            new_name='prati',
        ),
    ]
