# Generated by Django 4.0 on 2022-02-23 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_rename_pratitelji_tviteras_prati'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvit',
            name='tvit_komentari',
            field=models.ManyToManyField(blank=True, related_name='komentar_korisnik', through='main.Komentar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tvit',
            name='tvit_lajkovi',
            field=models.ManyToManyField(blank=True, related_name='tvit_korisnik', through='main.Lajk', to=settings.AUTH_USER_MODEL),
        ),
    ]
